baseURL = "https://howyi.github.io/"
languageCode = "ja-JP"
title = "howyi"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

  # Metadata for search engines and social sharing
  author = "howyi"
  shareImage = "images/background.jpg"
  twitterHandle = "howyi_lq"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background.jpg"
      position = "center center"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Develop"

      [[params.links.list1.link]]
        text = "GitHub"
        url = "https://github.com/howyi"

      [[params.links.list1.link]]
        text = "Speaker Deck"
        url = "https://speakerdeck.com/howyi"

      [[params.links.list1.link]]
        text = "DEV"
        url = "https://dev.to/howyi"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Email"
        url = "mailto::howyi.lq@gmail.com"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://twitter.com/howyi_lq"

      [[params.links.list2.link]]
        text = "Facebook"
        url = "https://www.facebook.com/howyi.lq"